# Content-based Recommendation with movies dataset

## Import necessary libraries

In [1]:
!pip install pymongo

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np
import math

In [3]:
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb+srv://baosurgeous:testDatabase@testcluster.dfxfjru.mongodb.net/?")
db = client["moviesDB"]
movies_collection = db["movies"]
ratings_collection = db["ratings"]
users_collection = db["users"]

def convert_collection_to_pandas_dataframe(collection):
    # Retrieve data from MongoDB
    data_from_mongo = collection.find({}, {"_id": 0})

    # Convert data to a list of dictionaries
    data_list = list(data_from_mongo)

    # Convert to DataFrame
    df = pd.DataFrame(data_list)
    
    return df
    
movies_df = convert_collection_to_pandas_dataframe(movies_collection)
ratings_df = convert_collection_to_pandas_dataframe(ratings_collection)
users_df = convert_collection_to_pandas_dataframe(users_collection)

In [4]:
movies_df.head()

adult belongs_to_collection    budget  \
0  False                  None   5000000   
1  False                  None  29000000   
2  False                  None    900000   
3  False    The Net Collection  22000000   
4  False                  None  34000000   

                                              genres homepage    id  \
0  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...           1024   
1  [{'id': 878, 'name': 'Science Fiction'}, {'id'...             63   
2  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...            880   
3  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...           1642   
4  [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...            241   

     imdb_id original_language        original_title  \
0  tt0110005                en    Heavenly Creatures   
1  tt0114746                en        Twelve Monkeys   
2  tt0112379                nl               Antonia   
3  tt0113957                en               The Net   
4  tt0110632                en  Natural Born Killers   

                                            overview  ... runtime  \
0  Wealthy and precocious teenager Juliet transfe...  ...     109   
1  In the year 2035, convict James Cole reluctant...  ...     129   
2  After World War II, Antonia and her daughter, ...  ...     102   
3  Angela Bennett is a freelance software enginee...  ...     114   
4  Two victims of traumatized childhoods become l...  ...     118   

                                    spoken_languages    status  \
0  [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
1  [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
2  [{'english_name': 'Dutch', 'iso_639_1': 'nl', ...  Released   
3  [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
4  [{'english_name': 'English', 'iso_639_1': 'en'...  Released   

                                             tagline                 title  \
0                       Not all angels are innocent.    Heavenly Creatures   
1                             The future is history.        Twelve Monkeys   
2  A motion picture that celebrates everything yo...        Antonia's Line   
3  No driver's license, no credit cards, no passp...               The Net   
4                    The media made them superstars.  Natural Born Killers   

   video popularity vote_average vote_count                     backdrop_path  
0  False   9.438042          6.9        299  /r6YVNhTEbPrurey0u4Ldk0WG3VA.jpg  
1  False  12.297305          7.4       2470  /1IWaKG7AWiYMhADxhGtnElDJAGI.jpg  
2  False   2.030174          7.2         26  /sOkUBkwq21ZEThCX7wboY2Xl3m5.jpg  
3  False  13.304342          5.6        359  /hPlL6FjbbZGZNfNaBePhOXSB9WY.jpg  
4  False  11.226856          6.9        927  /kn3zGuH4fhd1hG0CPFhFkWAP0tk.jpg  

[5 rows x 25 columns]

## Read and handle the dataset

### Create movie id mapping

In [5]:
# movies_df = pd.read_json('movies_with_backdrop_path.json')

In [6]:
movies_df

adult                      belongs_to_collection    budget  \
0     False                                       None   5000000   
1     False                                       None  29000000   
2     False                                       None    900000   
3     False                         The Net Collection  22000000   
4     False                                       None  34000000   
...     ...                                        ...       ...   
2817  False  Hercule Poirot (Peter Ustinov) Collection         0   
2818  False                                       None         0   
2819  False                                       None         0   
2820  False                        Adventures of a ...         0   
2821  False                                       None   1200000   

                                                 genres homepage     id  \
0     [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...            1024   
1     [{'id': 878, 'name': 'Science Fiction'}, {'id'...              63   
2     [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...             880   
3     [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...            1642   
4     [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...             241   
...                                                 ...      ...    ...   
2817  [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...            6105   
2818                      [{'id': 18, 'name': 'Drama'}]            1631   
2819  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...           74154   
2820                     [{'id': 35, 'name': 'Comedy'}]           86190   
2821  [{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...            2154   

        imdb_id original_language               original_title  \
0     tt0110005                en           Heavenly Creatures   
1     tt0114746                en               Twelve Monkeys   
2     tt0112379                nl                      Antonia   
3     tt0113957                en                      The Net   
4     tt0110632                en         Natural Born Killers   
...         ...               ...                          ...   
2817  tt0090914                en             Dead Man's Folly   
2818  tt0135024                fr        Une vraie jeune fille   
2819  tt0455663                te  నువ్వొస్తానంటే నేనొద్దంటానా   
2820  tt0074094                en  Adventures of a Taxi Driver   
2821  tt0099364                en    The Dark Side of the Moon   

                                               overview  ... runtime  \
0     Wealthy and precocious teenager Juliet transfe...  ...     109   
1     In the year 2035, convict James Cole reluctant...  ...     129   
2     After World War II, Antonia and her daughter, ...  ...     102   
3     Angela Bennett is a freelance software enginee...  ...     114   
4     Two victims of traumatized childhoods become l...  ...     118   
...                                                 ...  ...     ...   
2817  During a murder hunt game at a country house, ...  ...      90   
2818  Bored and restless, Alice spends much of her t...  ...      89   
2819  Siri and Sriram fall in love with each other a...  ...     165   
2820  Joe North is a London taxi driver who manages ...  ...      89   
2821  It is the year 2022. A mysterious systems fail...  ...      96   

                                       spoken_languages    status  \
0     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
1     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
2     [{'english_name': 'Dutch', 'iso_639_1': 'nl', ...  Released   
3     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
4     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
...                                                 ...       ...   
2817  [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
2818  [{'english_name': 'French', 'iso_639_1': 'fr',...  Released   
2819  [{'

In [7]:
index_list = movies_df.index.tolist()

In [8]:
index_list
index_list = [index + 1 for index in index_list]

In [9]:
movies_df['id_mapped'] = index_list

In [10]:
movies_df

adult                      belongs_to_collection    budget  \
0     False                                       None   5000000   
1     False                                       None  29000000   
2     False                                       None    900000   
3     False                         The Net Collection  22000000   
4     False                                       None  34000000   
...     ...                                        ...       ...   
2817  False  Hercule Poirot (Peter Ustinov) Collection         0   
2818  False                                       None         0   
2819  False                                       None         0   
2820  False                        Adventures of a ...         0   
2821  False                                       None   1200000   

                                                 genres homepage     id  \
0     [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...            1024   
1     [{'id': 878, 'name': 'Science Fiction'}, {'id'...              63   
2     [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...             880   
3     [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...            1642   
4     [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...             241   
...                                                 ...      ...    ...   
2817  [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...            6105   
2818                      [{'id': 18, 'name': 'Drama'}]            1631   
2819  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...           74154   
2820                     [{'id': 35, 'name': 'Comedy'}]           86190   
2821  [{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...            2154   

        imdb_id original_language               original_title  \
0     tt0110005                en           Heavenly Creatures   
1     tt0114746                en               Twelve Monkeys   
2     tt0112379                nl                      Antonia   
3     tt0113957                en                      The Net   
4     tt0110632                en         Natural Born Killers   
...         ...               ...                          ...   
2817  tt0090914                en             Dead Man's Folly   
2818  tt0135024                fr        Une vraie jeune fille   
2819  tt0455663                te  నువ్వొస్తానంటే నేనొద్దంటానా   
2820  tt0074094                en  Adventures of a Taxi Driver   
2821  tt0099364                en    The Dark Side of the Moon   

                                               overview  ...  \
0     Wealthy and precocious teenager Juliet transfe...  ...   
1     In the year 2035, convict James Cole reluctant...  ...   
2     After World War II, Antonia and her daughter, ...  ...   
3     Angela Bennett is a freelance software enginee...  ...   
4     Two victims of traumatized childhoods become l...  ...   
...                                                 ...  ...   
2817  During a murder hunt game at a country house, ...  ...   
2818  Bored and restless, Alice spends much of her t...  ...   
2819  Siri and Sriram fall in love with each other a...  ...   
2820  Joe North is a London taxi driver who manages ...  ...   
2821  It is the year 2022. A mysterious systems fail...  ...   

                                       spoken_languages    status  \
0     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
1     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
2     [{'english_name': 'Dutch', 'iso_639_1': 'nl', ...  Released   
3     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
4     [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
...                                                 ...       ...   
2817  [{'english_name': 'English', 'iso_639_1': 'en'...  Released   
2818  [{'english_name': 'French', 'iso_639_1': 'fr',...  Released   
2819  [{'english_name': 'Telugu', 'iso_639_1': 'te',...  Released   
2820  [{'english_name': 'English', '

### Generate the binary matrix for item's genres

In [11]:
movies_df['genres']

0       [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...
1       [{'id': 878, 'name': 'Science Fiction'}, {'id'...
2       [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...
3       [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...
4       [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...
                              ...                        
2817    [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...
2818                        [{'id': 18, 'name': 'Drama'}]
2819    [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...
2820                       [{'id': 35, 'name': 'Comedy'}]
2821    [{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...
Name: genres, Length: 2822, dtype: object

In [12]:
# Generate item profiles
movies_df['genre_list'] = movies_df['genres'].apply(lambda x: [item['name'] for item in x])

In [13]:
movies_df['genre_list']

0                                  [Drama, Fantasy]
1              [Science Fiction, Thriller, Mystery]
2                                   [Drama, Comedy]
3         [Crime, Drama, Mystery, Thriller, Action]
4                          [Crime, Thriller, Drama]
                           ...                     
2817           [Crime, Thriller, Mystery, TV Movie]
2818                                        [Drama]
2819                       [Drama, Comedy, Romance]
2820                                       [Comedy]
2821    [Horror, Action, Thriller, Science Fiction]
Name: genre_list, Length: 2822, dtype: object

In [14]:
items = movies_df[['id_mapped', 'title', 'release_date']].copy()

In [15]:
items.head()

id_mapped                 title release_date
0          1    Heavenly Creatures   1994-09-12
1          2        Twelve Monkeys   1995-12-29
2          3        Antonia's Line   1995-09-21
3          4               The Net   1995-07-28
4          5  Natural Born Killers   1994-08-26

In [16]:
genres_list = ['unknown', 'Action', 'Adventure', 'Animation', 'Children\'s',
               'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
               'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

binary_matrix = movies_df['genre_list'].apply(lambda x: [1 if genre in x else 0 for genre in genres_list])
binary_df = pd.DataFrame(binary_matrix.values.tolist(), columns=genres_list)

In [17]:
binary_matrix

0       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, ...
1       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...
2       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...
3       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, ...
4       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, ...
                              ...                        
2817    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...
2818    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...
2819    [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, ...
2820    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2821    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...
Name: genre_list, Length: 2822, dtype: object

In [18]:
binary_df

unknown  Action  Adventure  Animation  Children's  Comedy  Crime  \
0           0       0          0          0           0       0      0   
1           0       0          0          0           0       0      0   
2           0       0          0          0           0       1      0   
3           0       1          0          0           0       0      1   
4           0       0          0          0           0       0      1   
...       ...     ...        ...        ...         ...     ...    ...   
2817        0       0          0          0           0       0      1   
2818        0       0          0          0           0       0      0   
2819        0       0          0          0           0       1      0   
2820        0       0          0          0           0       1      0   
2821        0       1          0          0           0       0      0   

      Documentary  Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  \
0               0      1        1          0       0        0        0   
1               0      0        0          0       0        0        1   
2               0      1        0          0       0        0        0   
3               0      1        0          0       0        0        1   
4               0      1        0          0       0        0        0   
...           ...    ...      ...        ...     ...      ...      ...   
2817            0      0        0          0       0        0        1   
2818            0      1        0          0       0        0        0   
2819            0      1        0          0       0        0        0   
2820            0      0        0          0       0        0        0   
2821            0      0        0          0       1        0        0   

      Romance  Sci-Fi  Thriller  War  Western  
0           0       0         0    0        0  
1           0       0         1    0        0  
2           0       0         0    0        0  
3           0       0         1    0        0  
4           0       0         1    0        0  
...       ...     ...       ...  ...      ...  
2817        0       0         1    0        0  
2818        0       0         0    0        0  
2819        1       0         0    0        0  
2820        0       0         0    0        0  
2821        0       0         1    0        0  

[2822 rows x 19 columns]

In [19]:
items_df = pd.concat([items, binary_df], axis=1)

In [20]:
items_df

id_mapped                        title release_date  unknown  Action  \
0             1           Heavenly Creatures   1994-09-12        0       0   
1             2               Twelve Monkeys   1995-12-29        0       0   
2             3               Antonia's Line   1995-09-21        0       0   
3             4                      The Net   1995-07-28        0       1   
4             5         Natural Born Killers   1994-08-26        0       0   
...         ...                          ...          ...      ...     ...   
2817       2818             Dead Man's Folly   1986-01-08        0       0   
2818       2819            A Real Young Girl   1976-01-01        0       0   
2819       2820   Nuvvostanante Nenoddantana   2005-01-14        0       0   
2820       2821  Adventures of a Taxi Driver   1976-04-30        0       0   
2821       2822    The Dark Side of the Moon   1990-05-30        0       1   

      Adventure  Animation  Children's  Comedy  Crime  ...  Fantasy  \
0             0          0           0       0      0  ...        1   
1             0          0           0       0      0  ...        0   
2             0          0           0       1      0  ...        0   
3             0          0           0       0      1  ...        0   
4             0          0           0       0      1  ...        0   
...         ...        ...         ...     ...    ...  ...      ...   
2817          0          0           0       0      1  ...        0   
2818          0          0           0       0      0  ...        0   
2819          0          0           0       1      0  ...        0   
2820          0          0           0       1      0  ...        0   
2821          0          0           0       0      0  ...        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        1        0       0         1    0   
2             0       0        0        0        0       0         0    0   
3             0       0        0        1        0       0         1    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
2817          0       0        0        1        0       0         1    0   
2818          0       0        0        0        0       0         0    0   
2819          0       0        0        0        1       0         0    0   
2820          0       0        0        0        0       0         0    0   
2821          0       1        0        0        0       0         1    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
2817        0  
2818        0  
2819        0  
2820        0  
2821        0  

[2822 rows x 22 columns]

### Map the new mapped-movie ids to ratings dataset

In [21]:
# ratings_df = pd.read_json('new_ratings.json')

In [22]:
ratings_df

user_id  movie_id  rating     timestamp
0            2       110     4.0  8.353555e+11
1            2       273     4.0  8.353558e+11
2            2       349     4.0  8.353554e+11
3            1      2193     2.0  1.260759e+12
4            2       377     3.0  8.353557e+11
...        ...       ...     ...           ...
44897      672       253     2.0  1.700702e+09
44898      672       956     5.0  1.700702e+09
44899      672        11     5.0  1.700702e+09
44900      672       681     5.0  1.700703e+09
44901      672       296     4.5  1.700703e+09

[44902 rows x 4 columns]

In [23]:
ratings_df = pd.merge(ratings_df, movies_df[['id_mapped', 'id']], left_on='movie_id',right_on='id', how='left')

In [24]:
ratings_df

user_id  movie_id  rating     timestamp  id_mapped    id
0            2       110     4.0  8.353555e+11        171   110
1            2       273     4.0  8.353558e+11       1467   273
2            2       349     4.0  8.353554e+11       1642   349
3            1      2193     2.0  1.260759e+12        563  2193
4            2       377     3.0  8.353557e+11        234   377
...        ...       ...     ...           ...        ...   ...
44897      672       253     2.0  1.700702e+09        687   253
44898      672       956     5.0  1.700702e+09       1566   956
44899      672        11     5.0  1.700702e+09        110    11
44900      672       681     5.0  1.700703e+09        956   681
44901      672       296     4.5  1.700703e+09       1081   296

[44902 rows x 6 columns]

In [25]:
# # Drop the $oid from mongodb
# ratings_df.drop(columns=['_id'], inplace=True)

In [26]:
ratings_df

user_id  movie_id  rating     timestamp  id_mapped    id
0            2       110     4.0  8.353555e+11        171   110
1            2       273     4.0  8.353558e+11       1467   273
2            2       349     4.0  8.353554e+11       1642   349
3            1      2193     2.0  1.260759e+12        563  2193
4            2       377     3.0  8.353557e+11        234   377
...        ...       ...     ...           ...        ...   ...
44897      672       253     2.0  1.700702e+09        687   253
44898      672       956     5.0  1.700702e+09       1566   956
44899      672        11     5.0  1.700702e+09        110    11
44900      672       681     5.0  1.700703e+09        956   681
44901      672       296     4.5  1.700703e+09       1081   296

[44902 rows x 6 columns]

### Divide the ratings dataset into train and test

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
def split_data(df, test_size=0.1):
    train_set, test_set = pd.DataFrame(), pd.DataFrame()
    unique_users = ratings_df['user_id'].unique()

    for user in unique_users:
        user_data = df[df['user_id'] == user]
        train_user, test_user = train_test_split(user_data, test_size=test_size, random_state=42)

        train_set = pd.concat([train_set, train_user])
        test_set = pd.concat([test_set, test_user])

    return train_set, test_set

In [29]:
rating_train, rating_test = split_data(ratings_df, test_size=0.1)

In [30]:
rating_train

user_id  movie_id  rating     timestamp  id_mapped   id
236          2       552     3.0  8.353559e+11        822  552
95           2       223     1.0  8.353557e+11         46  223
330          2       509     4.0  8.353557e+11        502  509
13           2       592     5.0  8.353554e+11        979  592
372          2       319     1.0  8.353559e+11        138  319
...        ...       ...     ...           ...        ...  ...
44900      672       681     5.0  1.700703e+09        956  681
44897      672       253     2.0  1.700702e+09        687  253
44899      672        11     5.0  1.700702e+09        110   11
44898      672       956     5.0  1.700702e+09       1566  956
44901      672       296     4.5  1.700703e+09       1081  296

[40107 rows x 6 columns]

In [31]:
rating_test

user_id  movie_id  rating     timestamp  id_mapped    id
0            2       110     4.0  8.353555e+11        171   110
6            2       144     3.0  8.353560e+11        268   144
203          2       235     3.0  8.353557e+11        349   235
14           2       593     3.0  8.353555e+11        784   593
328          2       186     3.0  8.353557e+11       1601   186
...        ...       ...     ...           ...        ...   ...
44584      667       345     5.0  8.472717e+11        472   345
44757      667       551     3.0  8.472720e+11        489   551
44881      667        25     2.0  8.472715e+11       1553    25
44883      668      1213     5.0  9.936134e+11        899  1213
44895      672       671     4.0  1.700702e+09        990   671

[4795 rows x 6 columns]

In [32]:
rate_train = rating_train.to_numpy()
rate_test = rating_test.to_numpy()
print('Number of traing rates:', rate_train.shape[0])
print('Number of test rates:', rate_test.shape[0])

Number of traing rates: 40107
Number of test rates: 4795


In [33]:
rate_train

array([[2.00000000e+00, 5.52000000e+02, 3.00000000e+00, 8.35355860e+11,
        8.22000000e+02, 5.52000000e+02],
       [2.00000000e+00, 2.23000000e+02, 1.00000000e+00, 8.35355749e+11,
        4.60000000e+01, 2.23000000e+02],
       [2.00000000e+00, 5.09000000e+02, 4.00000000e+00, 8.35355719e+11,
        5.02000000e+02, 5.09000000e+02],
       ...,
       [6.72000000e+02, 1.10000000e+01, 5.00000000e+00, 1.70070178e+09,
        1.10000000e+02, 1.10000000e+01],
       [6.72000000e+02, 9.56000000e+02, 5.00000000e+00, 1.70070162e+09,
        1.56600000e+03, 9.56000000e+02],
       [6.72000000e+02, 2.96000000e+02, 4.50000000e+00, 1.70070273e+09,
        1.08100000e+03, 2.96000000e+02]])

## Generate the items' feature vectors using tf-idf

In [34]:
X0 = items_df.values
X_train_counts = X0[:, -19:]

In [35]:
X_train_counts

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0]], dtype=object)

In [36]:
#tfidf
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=True, norm ='l2')
tfidf = transformer.fit_transform(X_train_counts.tolist()).toarray()

In [37]:
tfidf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.57603953, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.54392029, 0.        , ..., 0.50367126, 0.        ,
        0.        ]])

## Create the models for each user

In [38]:
import numpy as np
def get_items_rated_by_user(rate_matrix, user_id):
    """
    in each line of rate_matrix, we have infor: user_id, item_id, rating (scores), time_stamp
    we care about the first three values
    return (item_ids, scores) rated by user user_id
    """
    y = rate_matrix[:,0] # all users
    # item indices rated by user_id
    # we need to +1 to user_id since in the rate_matrix, id starts from 1 
    # while index in python starts friom 0
    ids = np.where(y == user_id + 1)[0] 
    item_ids = rate_matrix[ids, -2] - 1 # index starts from 0 
    scores = rate_matrix[ids, 2]
    return (item_ids, scores)

In [39]:
users = ratings_df['user_id'].unique().copy()

In [40]:
n_users = users.shape[0]
print('Number of users:', n_users)

Number of users: 672


In [41]:
from sklearn.linear_model import Ridge
from sklearn import linear_model

d = tfidf.shape[1] # data dimension
W = np.zeros((d, n_users))
b = np.zeros((1, n_users))

# rate train has the structure like this: oid (generate by mongodb), user_id, movie_id, rating, timestamp
for n in range(n_users):    
    ids, scores = get_items_rated_by_user(rate_train, n)
    ids = [int(i) for i in ids]  # Convert ids to integers
    print(n)
    print(scores)
    clf = Ridge(alpha=0.01, fit_intercept=True)
    Xhat = tfidf[ids, :]
    
    clf.fit(Xhat, scores) 
    W[:, n] = clf.coef_
    b[0, n] = clf.intercept_

0
[1.  4.  2.5 2.  2.5]
1
[3. 1. 4. 5. 1. 3. 3. 5. 3. 4. 5. 5. 3. 3. 4. 3. 5. 4. 3. 3. 4. 4. 3. 3.
 3. 3. 5. 4. 2. 4. 3. 5. 2. 4. 3. 4. 3. 3. 4. 5. 3. 4. 3. 3. 4. 4. 3. 4.
 4. 4. 5. 3.]
2
[3.  4.  3.  4.  4.  3.  3.5 3.  3.  5.  4.  3.  3.  4.5 4.  3.  3.5 4.
 3.5 4.5 5.  2. ]
3
[5. 4. 4. 4. 4. 3. 5. 4. 5. 5. 4. 5. 3. 5. 5. 4. 5. 3. 4. 4. 5. 5. 3. 3.
 5. 5. 5. 3. 5. 5. 5. 5. 5. 5. 5. 4. 4. 1. 5. 4. 3. 4. 4. 5. 5. 5. 5. 5.
 5. 3. 5. 3. 5. 5. 4. 3. 5. 4. 2. 2. 1. 3. 5. 4. 5. 5. 4. 5. 5. 4. 5. 5.
 1. 5. 3. 3. 4. 5. 5. 5. 5. 5. 5. 4. 3. 5. 5. 4. 5. 3. 4. 5. 5. 3. 4. 3.
 5. 5. 5. 5. 5.]
4
[4.5 3.  4.  4.5 2.5 4.  4.5 4.  3.5 5.  4.  4.5 4.  3.5 4.  4.  4.  3.5
 4.5 4.5 4.5 4.  4.  4.  3.5 4.  4.  4.  4.5 3.5 4.5 4.  3.5 3.5 4.  4.
 3.5 5.  5.  3.5 3.5 3.5 4.  3.5 4.  4.  4.5]
5
[4.5 4.  4.5 4.  3.  2.  4.  5.  4.  4.5 1.5 3.  3.  2.  2.  3.  4.  4.
 1.  2.  2.  4.  3.5 4.5 1.5 2. ]
6
[3. 3. 3. 2. 4. 4. 3. 3. 3. 3. 3. 4. 4. 4. 1. 3. 5. 3. 3. 3. 4. 4. 3. 2.
 3. 3. 4. 4. 5. 5. 4. 3. 4. 3. 3. 3

138
[5.  3.  1.  3.5 4.5 4.5 5.  4.  3.5 3.5 3.5 2.  4.  4.  5.  0.5 3.5 0.5
 4.5 4.  3.5 3.5 2. ]
139
[4.5 4.  4.5 4.5 0.5 5.  4.5 3.  3.5 4.5 4.  1.5 3.5 4.  3.  0.5 1.5 1. ]
140
[4. 2. 3. 3. 5. 5. 4. 3.]
141
[1. 2. 3. 1. 4. 3. 3. 3. 3. 4. 3. 5. 4. 5. 2. 1. 1. 4. 3. 3. 2.]
142
[5.  5.  4.5 1.  4.  3.  4.5 4.5 3.  5.  5.  1.5 3.5 3.  1.5 4.5 3.  4.5
 3.5 5.  3.5 4.  5.  5.  5.  2.  4.5 4.5 5.  3.  4.  4.5 4.5 4.  1.  4.5
 4.5]
143
[3. 5. 3. 3. 2. 5. 3. 5. 3. 4. 4. 4. 3. 2. 4. 5. 3. 5. 3. 3. 3. 3. 3. 3.
 5. 4. 4. 4.]
144
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 4. 5. 4. 5. 1. 3. 5. 5. 5. 5. 4. 4. 5.
 5. 3. 5.]
145
[3.  5.  5.  2.5 3.5 5.  4.5 4.  3.5 2.  3.  3.5 3.5 2.5 4.  4.  5.  1.
 3.5 3.5 3.5 3.  2.5 4.  4.5 3.5 4.  2.5]
146
[4.  4.5 4.  4.  3.5 5.  5.  5.  5.  5.  3.5 5.  4.5 4.  3.  4.  4.  2.
 4.  5.  5.  5. ]
147
[2.  4.  4.  4.  4.  5.  3.  5.  4.5 5.  3.5 5.  4.5 4.5 3.5 3.5 3.5 3.5
 3.  3.5 5.  4.  5.  3.5 3.5 5.  4.  4.  4.5 4.  2.  4.5 3.5 4.  4.  3.5
 3.5 5.  2.5 4.  4.  3.  4.

332
[5.  4.  4.5 4.5 4.5 5.  4.  3.5 4.5 4.  5.  2.5 3.5 4.5 4.  5.  4.  3.5
 3.5 5.  5.  4.5 4.  4.  5. ]
333
[3.  4.  4.  3.  3.5 4.  5.  5.  3.5 3.  5.  5.  3. ]
334
[2.5 3.5 3.5 2.5 5.  2. ]
335
[5. 3. 5. 3. 1. 1. 5. 1. 4. 1. 5. 5. 5. 3. 2.]
336
[1. 4. 4. 4. 5. 2.]
337
[4. 3. 3. 3. 4. 4. 3. 3. 3. 4. 3. 5. 3. 3. 3. 3. 3. 3. 4. 3. 2. 4. 4. 3.
 5. 4. 3. 3. 3. 4. 3. 3. 3. 3. 5. 4. 4. 3. 4.]
338
[4.5 5.  3.  4.5 4.5 4.  5.  4.5 4.5 4.  2.5 3.  5.  3.5 5.  4.5 3.  4.5
 5.  5.  3.  4.5 5.  3.5 4.  5.  4.5 4.  3.5 5. ]
339
[3.5 4.  4.  2.5 5.  3.5 3.  4.  5.  3.  5.  5. ]
340
[5.  4.  3.5 4.5 4.  4.5 5.  3.5]
341
[5. 3. 4. 4. 4. 5. 5. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 3. 5. 4. 4. 5. 4. 4.
 5. 3. 4. 3. 5. 3. 3. 2. 5. 5. 5. 3. 4. 4. 4. 4. 5. 5. 4. 5. 4. 4. 4. 3.
 5. 5. 5. 4. 5. 5. 5. 4. 5. 4. 4. 4. 4. 5. 4. 3. 4. 2. 5. 3. 4. 4. 5. 5.
 5. 4. 4. 5. 4. 5. 3. 4. 4. 4. 5. 5. 4. 5. 4. 4. 4. 3. 4. 4. 4. 4. 5.]
342
[4. 4. 5. 5. 2. 3. 4. 4. 4. 3. 4. 2. 5. 4. 4. 3. 3. 5. 3. 5. 4. 5. 5.]
343
[4. 5. 3. 2. 3

386
[3. 4. 4. 5. 3. 5. 3. 5. 5. 5. 4. 4. 5. 5. 4. 5. 5. 5. 5. 4. 4. 4. 4. 4.
 5. 5. 5. 5. 4. 5. 5. 5. 5. 3. 3. 4. 4. 5. 4. 4. 5. 4. 5. 4. 4. 4. 4. 5.
 5. 4. 4. 5. 4. 5. 4. 4. 4. 4. 4. 2. 4. 4. 1. 3. 5. 4. 4. 3. 4. 4. 3. 5.
 5. 4. 2. 4. 3. 4. 2. 4. 4. 3. 3. 5. 5. 4. 3. 3. 2. 4. 5. 4. 5. 5. 5. 5.
 5. 5. 5. 5. 4. 4. 4. 5. 5. 4. 5. 5. 4. 4. 5. 4. 4. 4. 3. 4. 5. 4.]
387
[4.5 5.  3.  4.5 2.  4.  4.  5.  4.  4.  3.  4.  3.  4.  4.  5.  4.  4.
 4.5 2.  3.  3.  3.  4.  5.  3.  3.  1.  5.  5.  5.  4.  3.  3.  4.  5.
 3.  3.  5.  4.  4.  2.  1.  4.  4.  3.  4.  2.  5.  5.  4.  4.  1.  4.
 3.  4.5 5.  2.  3.  4.  4.5 3.  4.  5.  4.  2.  4.  3.  3.5 4.  4.  4.
 4.  4.  3.  4.  4.  4.  2.  4.  4.  2.5 4.  1.  4.  4.  3.  3.  2.5 5.
 5.  4.  4.  4.  4.  4.  3.  4.  2.  4.  4.  5.  5.  3.5 4.5 2.  3.  4.
 4.  4.  5.  4.  4.  5.  4.  3.  3.  1.  4.  4.  3.  3.  1.  3.  4.  5.
 3.5 3.  5.  3.  4.5 4.  1.  4.5 5.  2.  4.  4.  3.  4.5 4.  2.  2.  5.
 2.5 5.  4.  5.  3.  4.  5.  5.  3.  5.  4.  3.  5.  4. 

 2.  4.  2.5 3.  4.  4.  3.  4.  3.  4.5 1. ]
529
[4. 2. 4. 5. 5. 4. 4. 4. 5. 1. 5. 3. 5. 4. 3. 4. 4. 5. 4. 2. 4. 3. 5. 3.
 5. 5. 2. 2. 5. 4. 2. 2. 2. 1. 5. 5. 5. 2. 5. 5. 5. 5. 2. 2.]
530
[4.  4.  0.5 1.  1.5 4.  4.  3.  3.5 0.5 4.  4.  3.  3.5 2.  2.  1.5 3.5
 3.5 3.5 3.5 3.5 0.5 1.  0.5 4.  2.  3.  3.5 2.  3.5 1.5 3.5 2.5 4.  4.
 4.  3.5 3.  2.5 3.5 1.5 3.5 3.5 3.5 4.  3.  4.5 0.5 3.  2.5 3.5 3.5 2.5]
531
[3.5 3.5 4.  3.5 4.5 3.  4.  4.  3.5 4.5 3.5 3.5 3.5 3.5 3.  3.5 4.  4.5
 3.  4.5]
532
[3. 3. 4. 3. 3. 3. 2. 2. 2. 3. 4. 4. 3. 4. 3. 2. 3. 2. 4. 4. 4. 4. 3. 4.
 4. 3. 2. 4. 4. 4. 2. 3. 3. 3. 4. 4. 2. 4. 4. 4. 2. 4. 4. 4. 3. 3. 1. 4.
 4. 3. 5. 3. 3. 5. 3. 3. 1. 3. 3. 3. 3. 3. 3. 5. 4. 4. 5. 1. 5. 3. 5. 3.
 4. 4. 2.]
533
[4. 3. 2. 3. 4. 4. 4. 3. 4. 4. 4. 3. 5. 4. 4. 3. 4. 4. 4. 3. 4. 2. 2. 4.
 4. 5. 3. 5. 4. 5. 5. 3. 3. 3. 2. 2. 5. 4. 4. 5. 3. 3. 2. 4. 3. 3. 3. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 2. 2. 4. 4. 4. 5. 2. 3. 4. 4. 4. 4. 3. 4. 4. 4.
 3. 3. 4. 2. 5. 4. 3. 4. 3. 4. 4. 3. 4. 3. 4. 4.

570
[4.  5.  4.  4.5 3.5 3.5 4.5 4.  3.5 2.  4.  4.5 3.5 4.5 4. ]
571
[4.5 3.5 4.5 4.  4.  4.5 4.  3.5 3.5 3.5 4.5 4.  5.  3.5 4.5 3.  4.5 3.5
 4.  5.  3.5 4.  3.  2.5 3.  3.  3.  4.  4.  3.5 3.  4.  4. ]
572
[4. 3. 4. 4. 4. 4. 3. 4. 5. 4. 3. 2. 4. 5. 4. 4. 1. 3.]
573
[4.5 4.  5.  3.5 4.5 3.  4.5 2.5 4.  3.  4.  4.5 3.  4.  4.  3.5 4.5 5.
 5.  4.5 4.  4.  4.  5.  4.  2.  3.5 3.  3.  3.5 3.  3.  3.5 3.5 3.  3.5
 3.5 3.  3.  2.5 4.5 4.  3.5 4.5 2.5 4.  3.  2.5 4.  4.  4.  4.  3.5 2.5
 3.5 0.5 4.  3.  3.5 2.5 2.  4.5 2.5 2.5 3.5 3.  3.5 4.  5.  4.5 3.5 3.
 1.  3.  2.5 4.5 3.5 4.5 4.  3.5 4.5 5.  0.5 1.  4.5 2.5 3.  3.  3.  3.
 3.5 2.5 5.  4.5 3.  4.  4.5 4.5 3.  4.5 4.  3.  3.5 3.  4.  3.5 2.5 3.5
 4.5 4.  3.5 4.  3.  2.5 3.  3.  3.  4.5 3.  3.5 4.5 4.  3.5 4.5 3.  3.5
 4.  2.5 4.  3.  3.  3.5]
574
[5. 2. 3. 5. 2. 4. 3. 3. 5. 4. 2. 5. 1. 3. 1. 4. 4. 4. 4. 4. 2. 5. 3. 4.
 4. 5. 2. 5. 3. 1. 4. 3. 3. 1. 4. 4. 2. 3. 4. 2. 4. 4. 4. 3. 1. 2. 2. 3.
 5. 4. 5. 4. 4. 2. 3. 5. 4. 3. 5. 4. 4. 5. 3. 2

In [42]:
# predicted scores
Yhat = tfidf.dot(W) + b

In [43]:
# Get 5 recommend movies for user_id 400
n = 399 # minus 1 since index starts from 0
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
ids = [int(i) for i in ids]  # Convert ids to integers

print('Rated movies ids :', ids)
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[:, n])

Rated movies ids : [256, 640, 170, 1188, 1622]
True ratings     : [4. 4. 5. 3. 3.]
Predicted ratings: [3.01 4.85 3.78 ... 3.75 4.09 4.09]


In [44]:
len(Yhat[:, n])

2822

## Create recommendation for each user

In [45]:
def top_5_recommendation_movies_for_user_n(Yhat, n):
    recommend_movies_id_mapped = np.argsort(Yhat[:, n])[-5:][::-1]
    recommendation_list = movies_df[movies_df['id_mapped'].isin(recommend_movies_id_mapped)]['id'].values
    return [int(recommendation_movie_id) for recommendation_movie_id in recommendation_list]

In [46]:
top_5_recommendation_movies_for_user_n(Yhat, 1)

[994, 2539, 27724, 58655, 4529]

In [47]:
# # Get the unique users in database
# users_id = users_df['id'].unique()
# # Update recommendation list for each user
# for user_id in users_id:
#     if user_id > n_users: 
#         continue
#     users_collection.update_one(
#     {"id": int(user_id)},
#     {"$set": {"recommendation_list": top_5_recommendation_movies_for_user_n(Yhat, int(user_id) - 1)}}
#     )

In [48]:
scores.shape

(5,)

In [49]:
Yhat[:, n].shape

(2822,)

## Evaluate the model

In [50]:
def evaluate(Yhat, rates, W, b):
    se = 0
    cnt = 0
    test_idx = 1
    for n in range(n_users):
        ids, scores_truth = get_items_rated_by_user(rates, n)
        ids = [int(i) for i in ids]  # Convert ids to integers
        scores_pred = Yhat[ids, n]
        e = scores_truth - scores_pred 
        se += (e*e).sum(axis = 0)
        cnt += e.size 
    return math.sqrt(se/cnt)

print('RMSE for training:', evaluate(Yhat, rate_train, W, b))
print('RMSE for test    :', evaluate(Yhat, rate_test, W, b))

RMSE for training: 0.856291047532383
RMSE for test    : 1.129340973906035
